config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get "/sessions/current" => "ember_devise_simple_auth/sessions#show"
  end

  devise_for :users, controllers: { sessions: 'ember_devise_simple_auth/sessions' }
  get 'welcome/index'

  root 'welcome#index'
  get 'donate' => 'donate'
  get 'play' => 'play'
  get 'market' => 'market'
  get 'try_on' => 'try_on'

  resources :items
  resources :avatars
  

end

app/models/avatar.rb
class Avatar < ActiveRecord::Base
  belongs_to :user
  has_many :equipped_items, dependent: :destroy
  has_many :items, through: :equipped_items
end

app/models/equipped_item.rb
class EquippedItem < ActiveRecord::Base
  belongs_to :avatar
  belongs_to :item
end

app/models/image.rb
# == Schema Information
#
# Table name: images
#
#  id          :integer          not null, primary key
#  item_id     :integer
#  image_layer :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#

class Image < ActiveRecord::Base
  mount_uploader :image_layer, ImageLayerUploader
  belongs_to :item
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images
  acts_as_taggable

	def self.search(gender, search)
	  if search
	    where("gender = ? OR gender = ? AND name ILIKE ?", gender.downcase, "neutral", "%#{search}%")
	  else
	    where("gender = ? OR gender = ?", gender.downcase, "neutral")
	  end
	end

	def self.starter_items()
		where("item_pack = ?", "starter")
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :avatar
  has_many :user_items, dependent: :destroy
  has_many :items, through: :user_items
end

app/models/user_item.rb
class UserItem < ActiveRecord::Base
  belongs_to :user
  belongs_to :item
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from ActionView::MissingTemplate do |exception|
    render "/layouts/application"
  end

  respond_to :html, :json
  
  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/controllers/avatar_controller.rb
class AvatarsController < ApplicationController
  before_action :authenticate_user!

  def index
    render json: current_user.avatar
  end

  def create
    @avatar = current_user.create_avatar(avatar_params)
     
      @avatar.save
        redirect_to edit_avatar_path(@avatar)
  end

  def new
    @avatar = Avatar.new
  end

  def edit
    @avatar = current_user.avatar
    @items = Item.search(@avatar.gender,params[:search])
    puts @avatar.gender
  end

  def destroy
    current_user.avatar.destroy
    redirect_to avatars_path
  end

  private
  def avatar_params
    params.require(:avatar).permit(:name, :gender, :skin_tone, :user_id)
  end

end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
  before_action :authenticate_user!

  def index
    @avatar = current_user.avatar
  end

  def create
    @avatar = current_user.create_avatar(avatar_params)
     
      @avatar.save
        redirect_to edit_avatar_path(@avatar)
  end

  def new
    @avatar = Avatar.new
    gon.avatar = @avatar
  end

  def edit
    @avatar = current_user.avatar
    gon.avatar = @avatar
    @items = current_user.items
    gon.items = @items
  end

  def show
    #todo
  end

  def update
    @avatar = Avatar.find(params[:id])

    respond_to do |format|
      if @avatar.update(avatar_params)
        format.html { redirect_to @avatar, notice: 'Avatar was successfully updated.' }
        format.json { render :nothing => true }
      else
        format.html { render action: "edit" }
        format.json { render json: @avatar.errors, status: :unprocessable_entity }
      end
    end
  end

  def try
    @avatar = current_user.avatar
    gon.avatar = @avatar
    @items = Item.search(@avatar.gender,params[:search])
    gon.items = @items
  end

  def destroy
    current_user.avatar.destroy
    redirect_to avatars_path
  end

  private
  def avatar_params
    params.require(:avatar).permit(:name, :gender, :skin_tone, :user_id)
  end

end

app/controllers/donate_controller.rb
class DonateController < ApplicationController
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  #require authentication to a create new item, or edit or destroy an existing one
  before_action :authenticate_user!,
    :only => [:new, :destroy, :edit]

  #display all items for the item catalog
  def index
    @items = Item.all
  end

  #instantiate a new item and build its images
  def new
    @item = Item.new
    @image = @item.images.build
  end

  def create
    @item = Item.new(item_params)
    respond_to do |format|
      if @item.save
        params[:images]['image_layer'].each do |a|
          @image = @item.images.create!(:image_layer => a, :item_id => @item.id)
        end
        format.html { redirect_to @item, notice: 'Post was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def edit
    #todo
  end

  def show
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])

    if @item.update(item_params)
      redirect_to @item
    else
      render 'edit'
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    redirect_to items_path
  end

  private
  def item_params
    params.require(:item).permit(:name, images_attributes: [:id, :item_id, :image_layer])
  end
end

app/controllers/market_controller.rb
class MarketController < ApplicationController
	def market
    respond_to do |format|
      format.html { render }
      format.json { render }
    end
  end
end

app/controllers/play_controller.rb
class PlayController < ApplicationController
	def play
	end
end

app/controllers/try_on_controller.rb
class TryOnController < ApplicationController
	def try_on
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/donate_helper.rb
module DonateHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/market_helper.rb
module MarketHelper
end

app/helpers/play_helper.rb
module PlayHelper
end

app/helpers/try_on_helper.rb
module TryOnHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<%= form_for @item, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :category, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :category, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :gender, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :gender, :class => 'form-control' %>
    </div>
  </div>

  
  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            items_path, :class => 'btn btn-default' %>
 
<% end %>

app/views/items/edit.html.erb
<%- model_class = Item -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/items/index.html.erb
<%- model_class = Item -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:category) %></th>
      <th><%= model_class.human_attribute_name(:gender) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= link_to item.id, item_path(item) %></td>
        <td><%= item.name %></td>
        <td><%= item.category %></td>
        <td><%= item.gender %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_item_path(item), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      item_path(item),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_item_path,
            :class => 'btn btn-primary' %>

app/views/items/new.html.erb
<%- model_class = Item -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/items/show.html.erb
<%- model_class = Item -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @item.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:category) %>:</strong></dt>
  <dd><%= @item.category %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gender) %>:</strong></dt>
  <dd><%= @item.gender %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              items_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_item_path(@item), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              item_path(@item),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>